// Package complete embeds the bash/zsh/fish completion scripts. The scripts
// call the hidden "adrm __complete" subcommand, which queries the live
// database for dynamic candidates (trash ids, original names, enum values).
package complete

// Bash returns the bash completion script.
func Bash() string {
	return `# >>> adrm bash completion (generated by 'adrm completions bash') >>>
_adrm_complete() {
    local cur cand nofiles=0
    cur="${COMP_WORDS[COMP_CWORD]}"
    cand="$("${ADRM_ADRM_BIN:-adrm}" __complete bash ${COMP_WORDS[@]:1} 2>/dev/null)"
    if [ -n "$cand" ]; then
        case "$cand" in
            *__nofiles__*) nofiles=1; cand="${cand//__nofiles__/}" ;;
        esac
        COMPREPLY=( $(compgen -W "$cand" -- "$cur") )
        [ "$nofiles" = 1 ] && return 0
    fi
    COMPREPLY+=( $(compgen -f -- "$cur") )
    return 0
}
complete -o default -F _adrm_complete adrm
complete -o default -F _adrm_complete rm
# <<< adrm bash completion <<<
`
}

// Zsh returns the zsh completion script.
func Zsh() string {
	return `#compdef adrm rm
# >>> adrm zsh completion (generated by 'adrm completions zsh') >>>
_adrm() {
  local -a args out
  args=(${words[1,$CURRENT]})
  out=("${(@f)$(${ADRM_ADRM_BIN:-adrm} __complete zsh "${args[@]}" 2>/dev/null)}")
  out=(${out:#__nofiles__})
  if (( ${#out} )); then
    _describe -t adrm 'adrm' out
    return 0
  fi
  _files
}
compdef _adrm adrm
compdef _adrm rm
# <<< adrm zsh completion <<<
`
}

// Fish returns the fish completion script.
func Fish() string {
	return `# >>> adrm fish completion (generated by 'adrm completions fish') >>>
function __adrm_fish_complete
    set -l bin adrm
    if set -q ADRM_ADRM_BIN
        set bin $ADRM_ADRM_BIN
    end
    set -l toks (commandline -opc) (commandline -ct)
    $bin __complete fish $toks 2>/dev/null
end
complete -c adrm -a '(__adrm_fish_complete)'
complete -c rm -a '(__adrm_fish_complete)'
# <<< adrm fish completion <<<
`
}

// FileName returns the conventional file name for a shell's completion.
func FileName(shell string) string {
	switch shell {
	case "zsh":
		return "_adrm"
	case "fish":
		return "adrm.fish"
	default:
		return "adrm.bash"
	}
}
