#!/usr/bin/env bash

REPO="wubinstu/adrm"
COMPLETION_URL="https://raw.githubusercontent.com/${REPO}/main/adrm-completion.bash"

OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
    Linux)  PLATFORM="linux" ;;
    Darwin) PLATFORM="macos" ;;
    *)      echo "Error: Unsupported OS: $OS" >&2; exit 1 ;;
esac

case "$ARCH" in
    x86_64|amd64)  ARCH_NAME="x86_64" ;;
    aarch64|arm64) ARCH_NAME="arm64" ;;
    *)             echo "Error: Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

BINARY_NAME="adrm-${PLATFORM}-${ARCH_NAME}"
DOWNLOAD_URL="https://github.com/${REPO}/releases/latest/download/${BINARY_NAME}"

echo "=== adrm installer ==="
echo ""

if ! [ -t 0 ]; then
    exec 0</dev/tty
fi

read -rp "Binary install location [default: ~/.local/bin]: " INSTALL_DIR
if [ -z "$INSTALL_DIR" ]; then
    INSTALL_DIR="$HOME/.local/bin"
fi
INSTALL_DIR="${INSTALL_DIR/#\~/$HOME}"

read -rp "adrm home directory [default: ~/.adrm]: " ADRM_HOME
if [ -z "$ADRM_HOME" ]; then
    ADRM_HOME="$HOME/.adrm"
fi
ADRM_HOME="${ADRM_HOME/#\~/$HOME}"
ADRM_HOME="${ADRM_HOME%/}"

read -rp "Create 'rm' alias and shell completion? [Y/n]: " CREATE_ALIAS
if [ -z "$CREATE_ALIAS" ]; then
    CREATE_ALIAS="y"
fi

echo ""
echo "Installing adrm..."
echo ""

mkdir -p "$INSTALL_DIR"

echo "Downloading ${BINARY_NAME}..."
curl -fsSL "$DOWNLOAD_URL" -o "${INSTALL_DIR}/adrm"
chmod +x "${INSTALL_DIR}/adrm"
echo "Downloaded to ${INSTALL_DIR}/adrm"

mkdir -p "${ADRM_HOME}"

echo "Downloading completion script..."
curl -fsSL "$COMPLETION_URL" -o "${ADRM_HOME}/adrm-completion.bash"
echo "Downloaded to ${ADRM_HOME}/adrm-completion.bash"

# Generate a per-installation completion file with correct paths
COMPLETION_FILE="${ADRM_HOME}/adrm-init.sh"
cat > "$COMPLETION_FILE" << ADRMEOF
# adrm shell initialization — auto-generated by install.sh
# Source this from .bashrc / .zshrc

export ADRM_HOME="${ADRM_HOME}"
alias rm="${INSTALL_DIR}/adrm"

if [ -n "\${BASH_VERSION:-}" ] || [ -n "\${ZSH_VERSION:-}" ]; then
    source "${ADRM_HOME}/adrm-completion.bash"
fi
ADRMEOF

echo "Generated ${COMPLETION_FILE}"

if [ "$CREATE_ALIAS" = "y" ] || [ "$CREATE_ALIAS" = "Y" ]; then
    SHELL_RC=""
    if [ -n "${ZSH_VERSION:-}" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -n "${BASH_VERSION:-}" ]; then
        SHELL_RC="$HOME/.bashrc"
    fi
    if [ -z "$SHELL_RC" ]; then
        SHELL_RC="$HOME/.bashrc"
    fi

    if [ -f "$SHELL_RC" ]; then
        sed -i '/# >>> adrm >>>/,/# <<< adrm <<</d' "$SHELL_RC"
        sed -i '\|source.*adrm-init\.sh|d' "$SHELL_RC"
    fi

    {
        echo ""
        echo "# >>> adrm >>>"
        echo "source \"${COMPLETION_FILE}\""
        echo "# <<< adrm <<<"
    } >> "$SHELL_RC"

    echo "Added source to ${SHELL_RC}"
fi

# Run --default to generate config if not present
if [ ! -f "${ADRM_HOME}/config" ]; then
    echo ""
    echo "Generating default configuration..."
    ADRM_HOME="$ADRM_HOME" "${INSTALL_DIR}/adrm" --default
fi

echo ""
echo "adrm installed successfully!"
echo ""
echo "  Binary:     ${INSTALL_DIR}/adrm"
echo "  Home:       ${ADRM_HOME}"
echo "  Completion: ${ADRM_HOME}/adrm-completion.bash"
echo "  Init:       ${COMPLETION_FILE}"
echo "  Config:     ${SHELL_RC:-<not modified>}"
echo ""
echo "Run 'source ${SHELL_RC}' or start a new shell to use adrm."
echo ""
echo "Quick start:"
echo "  adrm --default     # generate default config"
echo "  adrm --help        # show help"
