package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/wubinstu/adrm/internal/complete"
	"github.com/wubinstu/adrm/internal/i18n"
)

// markers bracket everything adrm writes into shell rc files, so uninstall
// can remove exactly what install added and nothing else.
const (
	rcMarkBegin = "# >>> adrm >>>"
	rcMarkEnd   = "# <<< adrm <<<"
)

// shellProfile describes one supported shell and its rc file.
type shellProfile struct {
	Shell string
	Rc    string
	Fish  bool
}

// shellProfiles lists the rc files adrm manages.
func shellProfiles(home string) []shellProfile {
	return []shellProfile{
		{"bash", filepath.Join(home, ".bashrc"), false},
		{"zsh", filepath.Join(home, ".zshrc"), false},
		{"fish", filepath.Join(home, ".config", "fish", "config.fish"), true},
	}
}

// cmdSetup installs or removes the shell integration.
func (a *app) cmdSetup(args []string) int {
	p := newParser()
	specs := concatSpecs(commonSpecs, []optSpec{
		{long: "install"}, {long: "uninstall"}, {long: "status"},
		{long: "alias"}, {long: "no-alias"},
		{long: "completion"}, {long: "no-completion"},
		{long: "cron"}, {long: "no-cron"},
		{long: "purge-home"}, {long: "yes", short: "y"},
		{long: "shells", takesValue: true},
	})
	if err := p.parse(args, specs); err != nil {
		return a.fail(err)
	}
	if p.has("help") || (!p.has("install") && !p.has("uninstall") && !p.has("status")) {
		a.printHelp([]string{"setup"})
		return 0
	}
	if err := a.applyCommon(p); err != nil {
		return a.fail(err)
	}
	switch {
	case p.has("install"):
		return a.setupInstall(p)
	case p.has("uninstall"):
		return a.setupUninstall(p)
	case p.has("status"):
		return a.setupStatus(p)
	}
	return 0
}

func (a *app) setupInstall(p *parser) int {
	if err := a.cfg.EnsureHome(); err != nil {
		return a.fail(err)
	}
	home, err := userHomeDir()
	if err != nil {
		return a.fail(err)
	}
	wantAlias := !p.has("no-alias")
	wantCompletion := !p.has("no-completion")
	shells := a.selectedShells(p)

	// 1. completion scripts
	compDir := filepath.Join(a.cfg.Home, "completions")
	if wantCompletion {
		if err := os.MkdirAll(compDir, 0o700); err != nil {
			return a.fail(err)
		}
		for _, sh := range shells {
			var script, name string
			switch sh {
			case "zsh":
				script, name = complete.Zsh(), complete.FileName("zsh")
			case "fish":
				script, name = complete.Fish(), complete.FileName("fish")
			default:
				script, name = complete.Bash(), complete.FileName("bash")
			}
			path := filepath.Join(compDir, name)
			if err := os.WriteFile(path, []byte(script), 0o644); err != nil {
				return a.fail(err)
			}
			fmt.Fprintf(a.out, i18n.Tr("已写入补全脚本: %s\n", "wrote completion script: %s\n"), path)
		}
	}

	// 2. init file sourced by every shell block
	initPath := filepath.Join(a.cfg.Home, "adrm-init.sh")
	var init strings.Builder
	fmt.Fprintf(&init, "# adrm shell integration (generated by 'adrm setup --install')\n")
	fmt.Fprintf(&init, "export ADRM_HOME=%q\n", a.cfg.Home)
	if wantAlias {
		fmt.Fprintf(&init, "alias rm='adrm'\n")
	}
	if err := os.WriteFile(initPath, []byte(init.String()), 0o644); err != nil {
		return a.fail(err)
	}
	fmt.Fprintf(a.out, i18n.Tr("已写入初始化脚本: %s\n", "wrote init script: %s\n"), initPath)

	// 3. rc file blocks
	for _, prof := range shellProfiles(home) {
		if !containsStr(shells, prof.Shell) {
			continue
		}
		if _, err := os.Stat(prof.Rc); err != nil && !os.IsNotExist(err) {
			continue
		}
		block := rcBlock(prof, a.cfg.Home, wantAlias, wantCompletion)
		if err := appendRcBlock(prof.Rc, block); err != nil {
			return a.fail(err)
		}
		fmt.Fprintf(a.out, i18n.Tr("已更新 %s\n", "updated %s\n"), prof.Rc)
	}

	// 4. optional cron/systemd timer for lazy gc
	if p.has("cron") {
		a.installCron()
	}
	fmt.Fprintln(a.out, i18n.Tr("安装完成。打开新终端或执行 'source ~/.bashrc' 后生效。",
		"done. open a new shell or run 'source ~/.bashrc' to activate."))
	return 0
}

func (a *app) selectedShells(p *parser) []string {
	if v := p.val("shells"); v != "" {
		var out []string
		for _, s := range strings.Split(v, ",") {
			s = strings.TrimSpace(strings.ToLower(s))
			if s == "bash" || s == "zsh" || s == "fish" {
				out = append(out, s)
			}
		}
		if len(out) > 0 {
			return out
		}
	}
	// auto-detect from $SHELL, default bash
	if sh := os.Getenv("SHELL"); sh != "" {
		base := filepath.Base(sh)
		switch base {
		case "zsh", "fish":
			return []string{base}
		}
	}
	return []string{"bash"}
}

func containsStr(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

// rcBlock renders the managed block for one shell profile.
func rcBlock(prof shellProfile, home string, wantAlias, wantCompletion bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", rcMarkBegin)
	fmt.Fprintf(&b, "# adrm: shell integration managed by 'adrm setup' (remove with 'adrm setup --uninstall')\n")
	if prof.Fish {
		fmt.Fprintf(&b, "set -gx ADRM_HOME %q\n", home)
		if wantAlias {
			fmt.Fprintf(&b, "alias rm='adrm'\n")
		}
		if wantCompletion {
			fish := filepath.Join(home, "completions", complete.FileName("fish"))
			fmt.Fprintf(&b, "test -f %q; and source %q\n", fish, fish)
		}
	} else {
		// POSIX shells (bash/zsh): "[ -r f ] && . f" -- never fish's "; and".
		fmt.Fprintf(&b, "export ADRM_HOME=%q\n", home)
		init := filepath.Join(home, "adrm-init.sh")
		fmt.Fprintf(&b, "[ -r %q ] && . %q\n", init, init)
		if wantCompletion {
			switch prof.Shell {
			case "zsh":
				zsh := filepath.Join(home, "completions", complete.FileName("zsh"))
				fmt.Fprintf(&b, "(( $+functions[compdef] )) || { autoload -Uz compinit && compinit -u }\n")
				fmt.Fprintf(&b, "[ -r %q ] && . %q\n", zsh, zsh)
			default:
				bash := filepath.Join(home, "completions", complete.FileName("bash"))
				fmt.Fprintf(&b, "[ -r %q ] && . %q\n", bash, bash)
			}
		}
	}
	fmt.Fprintf(&b, "%s\n", rcMarkEnd)
	return b.String()
}

// appendRcBlock removes an existing adrm block and appends the new one.
func appendRcBlock(rc, block string) error {
	data, err := os.ReadFile(rc)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	clean := removeRcBlock(string(data))
	sep := ""
	if len(clean) > 0 && !strings.HasSuffix(clean, "\n") {
		sep = "\n"
	}
	out := clean + sep + block
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	if err := os.MkdirAll(filepath.Dir(rc), 0o755); err != nil {
		return err
	}
	return os.WriteFile(rc, []byte(out), 0o644)
}

// removeRcBlock strips a previously installed adrm block (markers included).
func removeRcBlock(content string) string {
	lines := strings.Split(content, "\n")
	var out []string
	inBlock := false
	for _, ln := range lines {
		t := strings.TrimSpace(ln)
		if t == rcMarkBegin {
			inBlock = true
			continue
		}
		if t == rcMarkEnd {
			inBlock = false
			continue
		}
		if !inBlock {
			out = append(out, ln)
		}
	}
	res := strings.Join(out, "\n")
	// collapse triple blank lines left behind
	for strings.Contains(res, "\n\n\n") {
		res = strings.ReplaceAll(res, "\n\n\n", "\n\n")
	}
	return strings.TrimRight(res, "\n") + "\n"
}

func (a *app) setupUninstall(p *parser) int {
	home, err := userHomeDir()
	if err != nil {
		return a.fail(err)
	}
	// 1. rc blocks
	for _, prof := range shellProfiles(home) {
		data, err := os.ReadFile(prof.Rc)
		if err != nil {
			continue
		}
		if !strings.Contains(string(data), rcMarkBegin) {
			continue
		}
		clean := removeRcBlock(string(data))
		if err := os.WriteFile(prof.Rc, []byte(clean), 0o644); err != nil {
			return a.fail(err)
		}
		fmt.Fprintf(a.out, i18n.Tr("已清理 %s\n", "cleaned %s\n"), prof.Rc)
	}
	// 2. generated files inside the adrm home
	for _, f := range []string{"adrm-init.sh", "completions"} {
		path := filepath.Join(a.cfg.Home, f)
		if err := os.RemoveAll(path); err != nil {
			return a.fail(err)
		}
	}
	fmt.Fprintf(a.out, i18n.Tr("已删除 %s 下的 shell 集成文件。\n", "removed shell integration files under %s.\n"), a.cfg.Home)
	// 3. optionally the whole home (the trash itself)
	if p.has("purge-home") {
		if !p.has("yes") {
			fmt.Fprintf(a.out, i18n.Tr("警告: 将删除整个 adrm 主目录 %s (含回收站内所有文件!)\n",
				"warning: about to delete the whole adrm home %s (including everything in the trash!)\n"), a.cfg.Home)
			eng, err := a.engine()
			if err != nil {
				return a.fail(err)
			}
			if !eng.Confirm(i18n.Tr("确认删除?", "really delete?"), false) {
				fmt.Fprintln(a.out, i18n.Tr("已取消(回收站数据保留)。", "cancelled (trash data kept)."))
				return 0
			}
		}
		if err := os.RemoveAll(a.cfg.Home); err != nil {
			return a.fail(err)
		}
		fmt.Fprintf(a.out, i18n.Tr("已删除 %s\n", "removed %s\n"), a.cfg.Home)
	}
	fmt.Fprintln(a.out, i18n.Tr("卸载完成。如需删除二进制本身, 请手动移除安装路径下的 adrm。",
		"uninstall done. to remove the binary itself, delete the adrm executable from your install directory."))
	return 0
}

func (a *app) setupStatus(p *parser) int {
	home, err := userHomeDir()
	if err != nil {
		return a.fail(err)
	}
	fmt.Fprintf(a.out, i18n.Tr("adrm 主目录: %s\n", "adrm home: %s\n"), a.cfg.Home)
	if _, err := os.Stat(a.cfg.ConfigFile); err == nil {
		fmt.Fprintf(a.out, i18n.Tr("配置文件: %s\n", "config file: %s\n"), a.cfg.ConfigFile)
	} else {
		fmt.Fprintln(a.out, i18n.Tr("配置文件: 不存在 (运行 'adrm config --init' 生成)", "config file: missing (run 'adrm config --init')"))
	}
	for _, prof := range shellProfiles(home) {
		data, err := os.ReadFile(prof.Rc)
		if err != nil {
			continue
		}
		if strings.Contains(string(data), rcMarkBegin) {
			fmt.Fprintf(a.out, i18n.Tr("shell 集成: %s [已安装]\n", "shell integration: %s [installed]\n"), prof.Rc)
		} else if _, err := os.Stat(prof.Rc); err == nil {
			fmt.Fprintf(a.out, i18n.Tr("shell 集成: %s [未安装]\n", "shell integration: %s [not installed]\n"), prof.Rc)
		}
	}
	return 0
}

// installCron adds a daily systemd user timer or crontab entry running `adrm gc --quiet`.
func (a *app) installCron() {
	fmt.Fprintln(a.out, i18n.Tr("可选定时清理 (未自动安装, 手动执行其一即可):",
		"optional scheduled cleanup (not installed automatically; run one of these):"))
	fmt.Fprintln(a.out, "  systemd: systemd-run --user --on-calendar=daily adrm gc --quiet")
	fmt.Fprintln(a.out, "  cron:    (crontab -l; echo '0 9 * * * adrm gc --quiet') | crontab -")
}
