package config

import (
	"fmt"
	"os"
)

// Template returns the fully annotated default configuration. Comments are
// bilingual (Chinese first) so the file stays useful for everyone.
func Template() string {
	return `# adrm config / adrm 配置文件
# Generated by 'adrm config --init'. Run 'adrm config --show' for the effective config.

# ---- paths / 路径 ----
# home = "~/.adrm"              # adrm home / adrm 主目录 (env ADRM_HOME overrides)
# trash_dir = "~/.adrm/trash"   # where recycled files live / 回收站目录
# database = "~/.adrm/adrm.db"  # SQLite database / 数据库文件
# ignore_file = "~/.adrm/ignore"# gitignore-style rules / 忽略规则文件

# ---- retention / 有效期 ----
# How long items stay in the trash before 'adrm gc' may purge them.
# 回收站中文件的默认保留天数(天)
retention_days = 30

# Purge expired items automatically whenever adrm runs (a one-line notice is
# printed when something is actually removed; set false to require 'adrm gc').
# 运行任何命令时顺带清理过期项; false 则只提示, 不自动清理
auto_gc = true

# Ask once before recycling more than N files in a single command (rm -I).
# 单次回收超过 N 个文件时先询问一次
prompt_threshold = 3

# ---- safety / 安全 ----
# Refuse to recycle "/" (same as rm --preserve-root).
# 拒绝回收 "/"
preserve_root = true

# When a rename fails because source and trash live on different filesystems,
# copy the tree and delete the original afterwards.
# 跨文件系统时使用 复制+删除 兜底(而非直接失败)
copy_fallback = true

# ---- presentation / 显示 ----
# auto | zh | en  (auto follows LC_ALL/LANG; env ADRM_LANG overrides).
# In "en" mode every human-readable character is ASCII, safe for old terminals.
# 界面语言; en 模式下所有人类可读输出都是纯 ASCII
lang = auto

# auto | always | never  (env ADRM_COLOR overrides)
color = auto

# strftime-style layout used when printing timestamps.
# 时间显示格式
date_format = 2006-01-02 15:04:05

# Columns of 'adrm ls' (available: id path size mtime recycled expire left state mode owner trash).
# 'adrm ls' 显示的列及顺序
ls_columns = id, path, size, mtime, recycled, expire, left

# Columns of 'adrm log' (available: seq ts op id path size detail).
# 'adrm log' 显示的列及顺序
log_columns = seq, ts, op, id, path, detail

# Maximum rows printed by ls/log before the output is truncated with a notice.
# ls/log 最多输出的行数
max_list = 500
`
}

// WriteTemplate writes the annotated default config to path (refusing to
// overwrite unless force is set).
func WriteTemplate(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("config %s already exists (use --force to overwrite)", path)
	}
	if err := os.MkdirAll(dirOf(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(Template()), 0o600)
}

func dirOf(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' {
			return p[:i]
		}
	}
	return "."
}
